### ISSUE TITLE
0.2.23~precise deps

### ISSUE THREAD

**Issue by rpedde** [signalfx/collectd-build-ubuntu#80]
signalfx-collectd-plugin 0.2.23~precise packages (and probably others) is missing deps on python-six (for datadog listener):

```
signalfx-metadata: executing SIGCHLD workaround
dogstatsd: plugin init <collectd_dogstatsd.DogstatsDConfig object at 0x22c2e50>
Unhandled python exception in init callback: ImportError: No module named six.moves
Traceback (most recent call last):
  File "/opt/signalfx-collectd-plugin/signalfx_metadata.py", line 1583, in restore_sigchld
    DOGSTATSD_INSTANCE.init_callback()
  File "/opt/signalfx-collectd-plugin/collectd_dogstatsd.py", line 233, in init_callback
    self.sender = SignalfxPointSender(self.config, self.log)
  File "/opt/signalfx-collectd-plugin/collectd_dogstatsd.py", line 127, in __init__
    self.sfx = sfx.ingest(config.api_token)
  File "/opt/signalfx-collectd-plugin/signalfx/__init__.py", line 98, in ingest
    from . import ingest
  File "/opt/signalfx-collectd-plugin/signalfx/ingest.py", line 8, in <module>
    from six.moves import queue
ImportError: No module named six.moves
Initialization complete, entering read-loop.
```

**Comment by charliesignalfx** [comment]
Thank you for reporting this.  I will take a look and get back with you as soon as possible.

**Comment by charliesignalfx** [comment]
@rpedde We have a fix for this issue, and will be releasing it later this week.  Thank you for your help in identifying this issue.
